<a href="https://colab.research.google.com/github/practicalClerk/PBL-Project/blob/titanwork/phishing_ml_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## We converted raw URLs into numerical features, these features represent structural and semantic characteristics of phishing URLs, making the data suitable for machine learning models

## Importing the required Libraries...

In [9]:
import pandas as pd
import numpy as np
import re

## Load the dataset and the features...


In [11]:
dataset = pd.read_csv('phishing_raw_labeled_dataset.csv')
urls = dataset['url'].values
lables = dataset['label'].values

## Function to loop through all the urls row by row and extract features...
The following features are being extracted :

    
    URL Length
    Count of '.'
    Count of '/'
    Count of '-'
    Check whether 'https' is present or not
    Check whether IP Address is present or not
    Check Suspicious keywords are present ornot : 'login', 'verify', 'update', 'secure', 'account'


In [12]:
def extract_features(url):
  feature_lst=[]

  feature_lst.append(len(url))

  feature_lst.append(url.count('.'))

  feature_lst.append(url.count('/'))

  feature_lst.append(url.count('-'))

  feature_lst.append(1 if url.startswith('https') else 0)

  ip_pattern = re.compile(
        r'((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}'
    )
  feature_lst.append(1 if ip_pattern.search(url) else 0)

  suspicious_words = ['login', 'verify', 'update', 'secure', 'account']
  for word in suspicious_words:
        feature_lst.append(1 if word in url.lower() else 0)

  return feature_lst


## Applying Feature Extraction to all the URLs...

In [13]:
final_feature_lst =[]

for url in urls:
  final_feature_lst.append(extract_features(url))

X = np.array(final_feature_lst)
y = np.array(lables)

## DataFrame with feature names

In [14]:
feature_names = [
    'url_length',
    'num_dots',
    'num_slashes',
    'num_hyphens',
    'has_https',
    'has_ip',
    'kw_login',
    'kw_verify',
    'kw_update',
    'kw_secure',
    'kw_account'
]

features_df = pd.DataFrame(X, columns=feature_names)
features_df['label'] = y


In [15]:
features_df.to_csv('phishing_features.csv', index=False)
print("Feature extraction completed. File saved as phishing_features.csv")


Feature extraction completed. File saved as phishing_features.csv


## Data pre-processing:


# Importing necessary libraries

In [16]:
import numpy as np
import pandas as pd

# Loading the dataset and the x and y feature matrices

In [18]:
phishing_data = pd.read_csv('phishing_features.csv')

In [19]:
cat_features = phishing_data.select_dtypes(include = ['category','object']).columns

In [20]:
num_features = phishing_data.select_dtypes(include = ['int64','float64']).columns

In [21]:
print("Categorical data :",cat_features)

Categorical data : Index([], dtype='object')


In [22]:
print("numerical features :",num_features)

numerical features : Index(['url_length', 'num_dots', 'num_slashes', 'num_hyphens', 'has_https',
       'has_ip', 'kw_login', 'kw_verify', 'kw_update', 'kw_secure',
       'kw_account', 'label'],
      dtype='object')


In [23]:
x = phishing_data.iloc[:,:-1].values

In [24]:
y = phishing_data.iloc[:,-1].values

In [25]:
print(x)

[[11  1  0 ...  0  0  0]
 [12  1  0 ...  0  0  0]
 [12  1  0 ...  0  0  0]
 ...
 [13  1  0 ...  0  0  0]
 [61  2  3 ...  0  0  0]
 [87  1 12 ...  0  0  0]]


In [26]:
print(y)

[0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 0
 0 0 1 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 0 1 1 0 0
 1 1 0 1 0 1 0 1 1 1 1 0 0 0 0 1 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 0
 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 1 0 1 0 0 0 1
 0 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0
 1 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0
 0 1 0 1 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0
 1 0 1 1 1 1 0 0 1 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 0 0 0 0 1 1 1
 0 1 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 1 0
 0 1 1 0 0 0 0 1 1 1 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 0
 1 0 1 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 0 0 0 0 0
 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0
 0 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 0 0
 1 1 1 0 1 1 1 1 1 0 0 0 

# Identifying missing data(if any) and then handling them by filling the mean of that feature list.

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
x[:,1:12] = imputer.fit_transform(x[:,1:12])


In [28]:
print(x)

[[11  1  0 ...  0  0  0]
 [12  1  0 ...  0  0  0]
 [12  1  0 ...  0  0  0]
 ...
 [13  1  0 ...  0  0  0]
 [61  2  3 ...  0  0  0]
 [87  1 12 ...  0  0  0]]


# Splitting the dataset into train(80%) and test(20%) data-sets

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)


In [30]:
print(x_train)

[[12  2  0 ...  0  0  0]
 [46  2  0 ...  0  0  0]
 [11  1  0 ...  0  0  0]
 ...
 [11  1  0 ...  0  0  0]
 [30  3  2 ...  0  0  0]
 [11  1  0 ...  0  0  0]]


In [31]:
print(x_test)

[[34  1  3 ...  0  0  0]
 [24  1  3 ...  0  0  0]
 [26  3  2 ...  0  0  0]
 ...
 [32  2  2 ...  0  0  0]
 [ 9  1  0 ...  0  0  0]
 [13  1  0 ...  0  0  0]]


In [32]:
print(y_train)

[0 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1
 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 0 1 0 0 0
 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 0 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 0 1
 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 1
 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1
 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0
 0 1 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 1 1 0 1 1 0
 1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 1 1 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 1 0
 1 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 0 1
 0 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 0 0
 1 0 1 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 1
 1 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 0 1 

In [33]:
print(y_test)

[1 1 1 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 1 1 1 1 0 1 1 0 0 1 1 0 0 0
 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 1 1 1
 0 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0 1 1 0
 1 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 0
 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 1 1 1 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 0 1
 1 1 1 0 1 1 0 0 0 1 1 0 1 0 0]


# Feture Scaling to the following columns(using standardization)

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [36]:
print(x_test)

[[-0.10042535 -0.65383836  0.77502055 ... -0.06135239 -0.07088812
   0.        ]
 [-0.36795874 -0.65383836  0.77502055 ... -0.06135239 -0.07088812
   0.        ]
 [-0.31445206  1.48989396  0.26970968 ... -0.06135239 -0.07088812
   0.        ]
 ...
 [-0.15393203  0.4180278   0.26970968 ... -0.06135239 -0.07088812
   0.        ]
 [-0.76925883 -0.65383836 -0.74091207 ... -0.06135239 -0.07088812
   0.        ]
 [-0.66224547 -0.65383836 -0.74091207 ... -0.06135239 -0.07088812
   0.        ]]


In [37]:
print(x_train)

[[-0.68899881  0.4180278  -0.74091207 ... -0.06135239 -0.07088812
   0.        ]
 [ 0.22061472  0.4180278  -0.74091207 ... -0.06135239 -0.07088812
   0.        ]
 [-0.71575215 -0.65383836 -0.74091207 ... -0.06135239 -0.07088812
   0.        ]
 ...
 [-0.71575215 -0.65383836 -0.74091207 ... -0.06135239 -0.07088812
   0.        ]
 [-0.20743871  1.48989396  0.26970968 ... -0.06135239 -0.07088812
   0.        ]
 [-0.71575215 -0.65383836 -0.74091207 ... -0.06135239 -0.07088812
   0.        ]]


####Applying Logistic Regression(The Baseline model)

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [39]:
log_reg = LogisticRegression(max_iter=1000)

In [40]:
log_reg.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [41]:
y_pred = log_reg.predict(x_test)

In [42]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.975


In [43]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.98       102
           1       1.00      0.95      0.97        98

    accuracy                           0.97       200
   macro avg       0.98      0.97      0.97       200
weighted avg       0.98      0.97      0.97       200



In [44]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[102   0]
 [  5  93]]
