## We converted raw URLs into numerical features, these features represent structural and semantic characteristics of phishing URLs, making the data suitable for machine learning models

## Importing the required Libraries...

In [1]:
import pandas as pd
import numpy as np
import re

## Load the dataset and the features...


In [2]:
dataset = pd.read_csv('final_dataset.csv')
urls = dataset['url'].values
lables = dataset['label'].values

## Function to loop through all the urls row by row and extract features...
The following features are being extracted :

    
    URL Length
    Count of '.'
    Count of '/'
    Count of '-'
    Check whether 'https' is present or not
    Check whether IP Address is present or not
    Check Suspicious keywords are present ornot : 'login', 'verify', 'update', 'secure', 'account'


In [3]:
def extract_features(url):
  feature_lst=[]

  feature_lst.append(len(url))

  feature_lst.append(url.count('.'))

  feature_lst.append(url.count('/'))

  feature_lst.append(url.count('-'))

  feature_lst.append(1 if url.startswith('https') else 0)

  ip_pattern = re.compile(
        r'((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.|$)){4}'
    )
  feature_lst.append(1 if ip_pattern.search(url) else 0)

  suspicious_words = ['login', 'verify', 'update', 'secure', 'account']
  for word in suspicious_words:
        feature_lst.append(1 if word in url.lower() else 0)

  return feature_lst


## Applying Feature Extraction to all the URLs...

In [4]:
final_feature_lst =[]

for url in urls:
  final_feature_lst.append(extract_features(url))

X = np.array(final_feature_lst)
y = np.array(lables)

## DataFrame with feature names

In [5]:
feature_names = [
    'url_length',
    'num_dots',
    'num_slashes',
    'num_hyphens',
    'has_https',
    'has_ip',
    'kw_login',
    'kw_verify',
    'kw_update',
    'kw_secure',
    'kw_account'
]

features_df = pd.DataFrame(X, columns=feature_names)
features_df['label'] = y


In [6]:
features_df.to_csv('phishing_features.csv', index=False)
print("Feature extraction completed. File saved as phishing_features.csv")


Feature extraction completed. File saved as phishing_features.csv


## Data pre-processing:


# Importing necessary libraries

In [7]:
import numpy as np
import pandas as pd

# Loading the dataset and the x and y feature matrices

In [8]:
phishing_data = pd.read_csv('phishing_features.csv')

In [9]:
cat_features = phishing_data.select_dtypes(include = ['category','object']).columns

In [10]:
num_features = phishing_data.select_dtypes(include = ['int64','float64']).columns

In [11]:
print("Categorical data :",cat_features)

Categorical data : Index([], dtype='object')


In [12]:
print("numerical features :",num_features)

numerical features : Index(['url_length', 'num_dots', 'num_slashes', 'num_hyphens', 'has_https',
       'has_ip', 'kw_login', 'kw_verify', 'kw_update', 'kw_secure',
       'kw_account', 'label'],
      dtype='object')


In [13]:
x = phishing_data.iloc[:,:-1].values

In [14]:
y = phishing_data.iloc[:,-1].values

In [15]:
print(x)

[[22  2  2 ...  0  0  0]
 [21  2  2 ...  0  0  0]
 [25  2  2 ...  0  0  0]
 ...
 [75  2  3 ...  0  0  0]
 [53  2  1 ...  0  0  0]
 [56  2  4 ...  0  0  0]]


In [16]:
print(y)

[0 0 0 ... 1 1 1]


# Identifying missing data(if any) and then handling them by filling the mean of that feature list.

In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
x[:,1:12] = imputer.fit_transform(x[:,1:12])


In [18]:
print(x)

[[22  2  2 ...  0  0  0]
 [21  2  2 ...  0  0  0]
 [25  2  2 ...  0  0  0]
 ...
 [75  2  3 ...  0  0  0]
 [53  2  1 ...  0  0  0]
 [56  2  4 ...  0  0  0]]


# Splitting the dataset into train(80%) and test(20%) data-sets

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)


In [35]:
print(x_train)

[[ 9  1  0 ...  0  0  0]
 [35  2  1 ...  0  0  0]
 [50  1  2 ...  0  0  0]
 ...
 [14  1  0 ...  0  0  0]
 [22  1  1 ...  0  0  0]
 [ 9  1  0 ...  0  0  0]]


In [36]:
print(x_test)

[[  9   1   0 ...   0   0   0]
 [ 49   2   3 ...   0   0   0]
 [ 13   1   0 ...   0   0   0]
 ...
 [107   1   2 ...   0   0   0]
 [ 23   1   0 ...   0   0   0]
 [ 11   1   0 ...   0   0   0]]


In [37]:
print(y_train)

[0 1 1 ... 0 1 0]


In [38]:
print(y_test)

[0 1 0 ... 1 1 0]


# Feture Scaling to the following columns(using standardization)

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [25]:
print(x_test)

[[-0.72905815 -0.54428882 -0.72739012 ... -0.0295952  -0.0295952
  -0.04334464]
 [ 0.37904707  0.52098309  0.90622529 ... -0.0295952  -0.0295952
  -0.04334464]
 [-0.61824762 -0.54428882 -0.72739012 ... -0.0295952  -0.0295952
  -0.04334464]
 ...
 [ 1.98579962 -0.54428882  0.36168682 ... -0.0295952  -0.0295952
  -0.04334464]
 [-0.34122132 -0.54428882 -0.72739012 ... -0.0295952  -0.0295952
  -0.04334464]
 [-0.67365289 -0.54428882 -0.72739012 ... -0.0295952  -0.0295952
  -0.04334464]]


In [26]:
print(x_train)

[[-0.72905815 -0.54428882 -0.72739012 ... -0.0295952  -0.0295952
  -0.04334464]
 [-0.00878976  0.52098309 -0.18285165 ... -0.0295952  -0.0295952
  -0.04334464]
 [ 0.4067497  -0.54428882  0.36168682 ... -0.0295952  -0.0295952
  -0.04334464]
 ...
 [-0.59054499 -0.54428882 -0.72739012 ... -0.0295952  -0.0295952
  -0.04334464]
 [-0.36892395 -0.54428882 -0.18285165 ... -0.0295952  -0.0295952
  -0.04334464]
 [-0.72905815 -0.54428882 -0.72739012 ... -0.0295952  -0.0295952
  -0.04334464]]


####Applying Logistic Regression(The Baseline model)

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [52]:
log_reg = LogisticRegression(max_iter=1000, class_weight={0:1, 1:1.5})

In [53]:
log_reg.fit(x_train, y_train)

LogisticRegression(class_weight={0: 1, 1: 1.5}, max_iter=1000)

In [54]:
y_pred = log_reg.predict(x_test)

In [55]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9495


In [56]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95      1020
           1       0.97      0.93      0.95       980

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



In [57]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[990  30]
 [ 71 909]]


## Applying Decision Tree to the dataset :

In [58]:
"""#### Applying Decision Tree Classifier"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [59]:
dt_model = DecisionTreeClassifier(
    criterion='gini',        # or 'entropy'
    max_depth=10,            # prevents overfitting
    class_weight = {0:1,1:1.5},
    random_state=42
)

In [62]:
dt_model.fit(x_train, y_train)

DecisionTreeClassifier(class_weight={0: 1, 1: 1.5}, max_depth=10,
                       random_state=42)

In [63]:
y_pred_dt = dt_model.predict(x_test)

In [64]:
dt_accuracy = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Accuracy:", dt_accuracy)

print("\nDecision Tree Classification Report:")
print(classification_report(y_test, y_pred_dt))

print("\nDecision Tree Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

Decision Tree Accuracy: 0.9495

Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.98      0.95      1020
           1       0.98      0.92      0.95       980

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000


Decision Tree Confusion Matrix:
[[997  23]
 [ 78 902]]


## Applying Random Forest

In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [66]:
rf_model = RandomForestClassifier(
    n_estimators=100,          # number of trees
    max_depth=15,              # controls overfitting
    class_weight={0:1, 1:1.5}, # prioritize phishing
    random_state=42,
    n_jobs=-1                  # use all CPU cores
)

In [67]:
rf_model.fit(x_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 1.5}, max_depth=15, n_jobs=-1,
                       random_state=42)

In [68]:
y_pred_rf = rf_model.predict(x_test)

In [69]:
rf_accuracy = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", rf_accuracy)

print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

print("\nRandom Forest Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 0.95

Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.98      0.95      1020
           1       0.98      0.92      0.95       980

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000


Random Forest Confusion Matrix:
[[998  22]
 [ 78 902]]


In [70]:
comparison_data = {
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "Accuracy": [
        0.95,
        0.9495,
        0.95
    ],
    "Precision (Phishing)": [
        0.98,
        0.98,
        0.98
    ],
    "Recall (Phishing)": [
        0.92,
        0.92,
        0.92
    ],
    "F1-score (Phishing)": [
        0.95,
        0.95,
        0.95
    ]
}

In [71]:
comparison_df = pd.DataFrame(comparison_data)
comparison_df

,Model,Accuracy,Precision (Phishing),Recall (Phishing),F1-score (Phishing)
0,Logistic Regression,0.9500,0.98,0.92,0.95
1,Decision Tree,0.9495,0.98,0.92,0.95
2,Random Forest,0.9500,0.98,0.92,0.95
